[package]
name = "no-std"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
frand = { path = "../../", default-features = false, features = [
    "impl_rng_core",
] }
rand = "0.8.5"
