[package]
name = "frand"
version = "0.7.0"
edition = "2021"
authors = ["EngusMaze"]
description = "Blazingly fast random number generation library"
tags = ["rng", "random"]
repository = "https://github.com/engusmaze/fast-noise-lite-rs"
homepage = "https://github.com/engusmaze/fast-noise-lite-rs"
license = "Apache-2.0 OR MIT"
exclude = ["*.png"]
readme = "README.md"

[dev-dependencies]
image = { version = "0.24.6", default-features = false, features = ["png"] }
rand = { version = "0.8.5", features = ["small_rng"] }